"""Writes necessary operation dictionaries"""

import status_effects

player_defaults = {"AltrChance": 1, "AmbushChance": 1, "AtkStam": 1,
                   "BandagesStopBleed": True, "BleedChance": 20,
                   "BlckingThrshld": 0, "ContnrBtmRng": 1, "DeathHlth": 0,
                   "DefStamMod": 0, "EpicActnChance": 1, "EffDmg": 0,
                   "FleeRng": [-3, 3], "FtgueDmg": 1, "FtgueRate": 1,
                   "FtgueThrshld": 10, "FtgueTxt": True,
                   "GlncngBlwDmg(Plyr)": 1, "HngrInc": 1, "InvHoldLen": 10,
                   "KillHealChance": 1, "KillHealth": 5, "MaxDmgMod": 0,
                   "MaxGold": 20, "MealMod": 0, "MissChance": 0, "PotMod": 0, "PrlngStlth": 1,
                   "RestDeath": True, "RestSick": 5, "StamModXtra": 0, "SnkAtkMult": 2, "SnkStm": 4,
                   "ScrlDstrctChance": 1, "TireThrshld": 0, "TireHngr": 3,
                   "VrntChance": 1, "WlkngStamLoss": 1, "XPMod": 0,}
ALT_COMMANDS_LIST = ["WALK", "MOVE", "TRAVEL", "FORWARD", "FORWARDS", "LEFT",
                   "RIGHT", "BACK", "BACKWARD", "BACKWARDS",
                   "NORTH", "EAST", "SOUTH", "WEST", "FIGHT", "KILL", "HIT",
                   "HOLD", "WEAR", "OPEN", "INVESTIGATE", "BANDAGES",
                   "BATTLE", "DISCARD", "PICK UP",
]
ALT_COMMANDS = {#Directionals
              "WALK": "GO",
              "MOVE": "GO",
              "TRAVEL": "GO",
              "HEAD": "GO",
              "FORWARD": "N",
              "FORWARDS": "N",
              "LEFT": "W",
              "RIGHT": "E",
              "BACK": "S",
              "BACKWARD": "S",
              "BACKWARDS": "S",
              "NORTH": "N",
              "EAST": "E",
              "SOUTH": "S",
              "WEST": "W",
              #Attacks
              "BATTLE": "ATTACK",
              "FIGHT": "ATTACK",
              "KILL": "ATTACK",
              "HIT": "ATTACK",
              #Drops
              "DISCARD": "DROP",
              #Equips
              "HOLD": "EQUIP",
              "WEAR": "EQUIP",
              #Searches
              "OPEN": "SEARCH",
              "INVESTIGATE": "SEARCH",
              #Takes
              "PICK UP": "TAKE",
              #Uses
              #Misc
              "BANDAGES": "BANDAGE ROLL",
}
INTERPRET_COMPREHENSIONS = {"Monsters": {"Zombie": ["Grizzled Zombie", "Decrepit Zombie"],
                                       "Wraith": ["Dread Wraith"],
                                       "Skeleton": ["Shrieking Skeleton"],
                                       "Ghoul": ["Fetid Ghoul"],
                                       "Giant Rat": ["Giant Bloodied Rat"],
                                       "Rat": ["Giant Rat", "Giant Bloodied Rat"],
                                       "Wolf": ["Alpha Wolf"],
                                       "Wild Boar": ["Ferocious Boar"],
                                       "Boar": ["Wild Boar", "Ferocious Boar"],
                                       "Elk": ["Enraged Elk"],
                                       "Stag": ["Whitefell Stag"],
                                       "Fire Beetle": ["Giant Fire Beetle"],
                                       "Beetle": ["Giant Fire Beetle"],
                                       "Hawk": ["Giant Hawk", "Ancient Hawk"],
                                       "Wolf Spider": ["Giant Wolf Spider", "Starving Wolf Spider"],
                                       "Black Widow": ["Giant Black Widow", "Black Widow Brood Mother"],
                                       "Spider": ["Giant Wolf Spider", "Starving Wolf Spider", "Giant Black Widow", "Black Widow Brood Mother", "Stone-Fang Spider", "Tar-Fang Spider"],
                                       "Orc": ["Orc Berserker", "Orc Hunter", "Orc Sharpshooter", "Orc Prophet", "Orc Deathspeaker", "Orc Scout"],
                                       "Goblin": ["Goblin Youngling", "Goblin Prodigy", "Goblin Grunt", "Goblin Hermit", "Goblin Veteran", "Goblin Warrior", "Goblin General", "Goblin Warlord", "Goblin Lord"],
                                      },
                          "Containers": {"Cart": ["Abandoned Cart"],
                                         "Caravan": ["Avalanche-Buried Caravan"],
                                         "Farmhouse": ["Ransacked Farmhouse"],
                                         "Coinpurse": ["Abandoned Coinpurse"],
                                         "Nest": ["Eagle's Nest"],
                                         "Shipwreck": ["Ancient Shipwreck"],
                                         "Bowl": ["Overturned Bowl"],
                                         "Shrine": ["Wrecked Shrine"],
                                         "Grass": ["Tall Grass"],
                                         "Statue": ["Hollow-Mouthed Statue"],
                                         "Tower": ["Ancient Tower"],
                                         "Box": ["Sealed Box"],
                                        }
}
CONTAINERS = {"BARREL": {"Numbers": [1, 2, 3, 4, 5], "Biome": ["a Forest", "the Plains", "the Mountains", "some Ruins", "a Castle", "a Dungeon", "a Graveyard"],
                         "Holds": ["Usables", "Misc", "Misc"],
                        },
              "SACK": {"Numbers": [6, 7], "Biome": ["a Forest", "the Plains", "the Mountains", "some Ruins", "a Castle", "a Dungeon", "a Graveyard"],
                       "Holds": ["Gold", "Misc"],
                      },
              "CRATE": {"Numbers": [11, 12, 13, 14, 15], "Biome": ["a Forest", "the Plains", "the Mountains", "some Ruins", "a Castle", "a Dungeon", "a Graveyard"],
                        "Holds": ["Usables", "Misc", "Misc"],
                       },
              "EAGLE'S NEST": {"Numbers": [16], "Biome": ["a Forest", "the Mountains"],
                               "Holds": ["Misc"],
                              },
              "CHEST": {"Numbers": [21, 22, 23, 24, 25], "Biome": ["a Forest", "the Plains", "the Mountains", "some Ruins", "a Castle", "a Dungeon", "a Graveyard"],
                        "Holds": ["Gold", "Usables"],
                       },
              "HOLLOW TREE": {"Numbers": [26, 27, 28, 29, 30], "Biome": ["a Forest", "a Graveyard"],
                              "Holds": ["Usables", "Misc"],
                             },
              "CORPSE": {"Numbers": [31, 32, 33], "Biome": ["a Forest", "the Plains", "the Mountains", "some Ruins", "a Dungeon", "a Graveyard"],
                         "Holds": ["Gold", "Usables", "Misc"],
                        },
              "WINESKIN": {"Numbers": [34, 35], "Biome": ["a Dungeon", "a Castle"],
                           "Holds": ["Misc"],
                          },
              "HOLE": {"Numbers": [36, 37, 38], "Biome": ["a Forest", "the Plains", "the Mountains"],
                       "Holds": ["Misc"],
                      },
              "ANCIENT SHIPWRECK": {"Numbers": [39, 40], "Biome": ["the Plains"],
                                    "Holds": ["Gold", "Usables"],
                                   },
              "OVERTURNED BOWL": {"Numbers": [41, 42], "Biome": ["some Ruins", "a Dungeon"],
                                  "Holds": ["Gold", "Misc"],
                                 },
              "BACKPACK": {"Numbers": [43, 44, 45], "Biome": ["a Forest", "the Mountains"],
                           "Holds": ["Gold", "Usables", "Misc"],
                          },
              "WRECKED SHRINE": {"Numbers": [46, 47, 48], "Biome": ["some Ruins", "a Graveyard"],
                                 "Holds": ["Gold", "Usables"],
                                },
              "COFFIN": {"Numbers": [49, 50], "Biome": ["a Graveyard"],
                         "Holds":["Weapns", "Misc"],
                        },
              "VASE": {"Numbers": [51, 52, 53, 54, 55], "Biome": ["some Ruins", "a Castle", "a Dungeon"],
                       "Holds": ["Gold", "Misc"],
                      },
              "CHAMBER POT": {"Numbers": [56, 57, 58, 59, 60], "Biome": ["some Ruins", "a Dungeon"],
                              "Holds": ["Misc"],
                             },
              "ABANDONED COINPURSE": {"Numbers": [61, 62, 63, 64, 65], "Biome": ["a Forest", "the Plains", "the Mountains", "some Ruins", "a Castle", "a Dungeon", "a Graveyard"],
                                      "Holds": ["Gold"],
                                     },
              "RABBIT HOLE": {"Numbers": [66, 67, 68, 69, 70], "Biome": ["a Forest", "the Plains"],
                              "Holds": ["Misc"],
                             },
              "TALL GRASS": {"Numbers": [71, 72, 73, 74, 75], "Biome": ["a Forest", "the Plains"],
                             "Holds": ["Misc"],
                            },
              "ABANDONED CART": {"Numbers": [76, 77, 78, 79, 80], "Biome": ["a Forest", "the Plains", "the Mountains"],
                                 "Holds": ["Gold", "Usables", "Misc"],
                                },
              "AVALANCHE-BURIED CARAVAN": {"Numbers": [81, 82, 83], "Biome": ["the Mountains"],
                                           "Holds": ["Gold", "Usables", "Misc"],
                                          },
              "TENT": {"Numbers": [84, 85], "Biome": ["the Plains"],
                       "Holds": ["Usables", "Misc"],
                      },
              "DITCH": {"Numbers": [86, 87, 88, 89, 90], "Biome": ["the Plains"],
                        "Holds": ["Misc"],
                       },
              "HOLLOW-MOUTHED STATUE": {"Numbers": [91, 92, 93], "Biome": ["some Ruins"],
                                        "Holds": ["Usables"],
                                       },
              "RANSACKED FARMHOUSE": {"Numbers": [94, 95, 96], "Biome": ["a Forest", "the Plains"],
                                      "Holds": ["Gold", "Usables", "Misc"],
                                     },
              "ANCIENT TOWER": {"Numbers": [97, 98], "Biome": ["the Mountains"],
                                "Holds": ["Gold", "Usables"],
                               },
              "SHELVES": {"Numbers": [99], "Biome": ["a Dungeon"],
                          "Holds": ["Usables"],
                         },
              "SEALED BOX": {"Numbers": [100], "Biome": ["a Dungeon"],
                             "Holds": ["Usables"],
                            },
              "DYING OAK": {"Numbers": [], "Biome": [],
                            "Holds": ["Usables", "Usables", "Misc"],
                           },
              "BARK PILE": {"Numbers": [], "Biome": [],
                            "Holds": ["Misc", "Misc", "Usables"],
                           },
              "ASH PILE": {"Numbers": [], "Biome": [],
                           "Holds": ["Misc", "Misc", "Gold", "Gold", "Usables"],
                          },
             }
ITEMS = ["Old Bone", "Owl Pellet", "Shiny Stone", "Shredded Hood",
         "Dead Mouse", "Torn Parchment", "Hardened Twig", "Glass Shard",
         "Rabbit Foot", "Odd Leaf", "Rusty Nail", "Worn Shoe",
         "Wheel Axle", "Dirt Clod", "Love Letter", "Yellow Beetle",
         "Red Beetle", "Orange Beetle", "Green Beetle", "Blue Beetle",
         "Indigo Beetle", "Violet Beetle", "Worm Larvae", "Moth Larvae",
         "Strike-Stone", "Cloth Doll", "Broken Amulet", "Candlewick",
         "Moldy Tome", "Card Deck", "Wooden Dice", "Hawk Egg",
         "Sparrow Egg", "Egg Sac", "Damp String"]
player_vals = {"Actions": 0, "Ambushed": 0, "Attacked": 0, "Attacks": 0,
               "Bosses": 0, "Champions": 0, "Conversations": 0,
               "Cooked": 0, "Deaths": 0, "Discovered": 1, "Epic": 0,
               "Explored": 0, "Eaten": 0, "Fires": 0, "Fled": 0, "Kills": 0,
               "Searched": 0, "SneakTime": 0, "Used": 0
              }
BIOME_TRAV_DIFFICULTY = {"a Forest": 0, "the Plains": 0, "the Mountains": 3,
                         "some Ruins": 1, "a Castle": 0, "a Dungeon": 1,
                         "a Graveyard": 0
                        }
LEVELS = {2: 10, 3: 34, 4: 70, 5: 118, 6: 178, 7: 250, 8: 334, 9: 430, 10: 538,
        11: 658, 12: 790, 13: 934, 14: 1090, 15: 1258, 16: 1438, 17: 1630,
        18: 1834, 19: 2050, 20: 2278, 21: 2518, 22: 2770, 23: 3034, 24: 3310,
        25: 3598, 26: 3898, 27: 4210, 28: 4534, 29: 4870, 30: 5218, 31: 5578,
        32: 5950, 33: 6334, 34: 6730, 35: 7138, 36: 7558, 37: 7990, 38: 8434,
        39: 8890, 40: 9358, 41: 9838, 42: 10330, 43: 10834, 44: 11350,
        45: 11878, 46: 12418, 47: 12970, 48: 13534, 49: 14110, 50: 14698,
        51: 1000000000
}
EDIBLES = {"Raw Boar Meat": {"Sickening": True, "Satiating": True, "Bonus": 10, "Meal": False},
         "Raw Elk Leg": {"Sickening": True, "Satiating": True, "Bonus": 10, "Meal": False},
         "Raw Venison Steak": {"Sickening": True, "Satiating": True, "Bonus": 10, "Meal": False},
         "Roasted Boar Shank": {"Sickening": False, "Satiating": True, "Bonus": 30, "Meal": False},
         "Roasted Elk Leg": {"Sickening": False, "Satiating": True, "Bonus": 20, "Meal": False},
         "Venison Steak": {"Sickening": False, "Satiating": True, "Bonus": 20, "Meal": False},
         "Hawk Egg": {"Sickening": True, "Satiating": True, "Bonus": 2, "Meal": False},
         "Boiled Hawk Egg": {"Sickening": False, "Satiating": True, "Bonus": 5, "Meal": False},
         "Sparrow Egg": {"Sickening": True, "Satiating": True, "Bonues": 2, "Meal": False},
         "Boiled Sparrow Egg": {"Sickening": False, "Satiating": True, "Bonus": 5, "Meal": False},
         "Red Apple": {"Sickening": False, "Satiating": True, "Bonus": 5, "Meal": False},
         "Old Bone": {"Sickening": False, "Satiating": False, "Bonus": 0, "Meal": False},
         "Owl Pellet": {"Sickening": True, "Satiating": False, "Bonus": -2, "Meal": False},
         "Shiny Stone": {"Sickening": False, "Satiating": False, "Bonus": 0, "Meal": False},
         "Shredded Hood": {"Sickening": False, "Satiating": False, "Bonus": -1, "Meal": False},
         "Dead Mouse": {"Sickening": True, "Satiating": True, "Bonus": -3, "Meal": False},
         "Torn Parchment": {"Sickening": False, "Satiating": False, "Bonus": 0, "Meal": False},
         "Hardened Twig": {"Sickening": False, "Satiating": False, "Bonus": -2, "Meal": False},
         "Glass Shard": {"Sickening": True, "Satiating": False, "Bonus": -6, "Meal": False},
         "Rabbit Foot": {"Sickening": True, "Satiating": True, "Bonus": 0, "Meal": False},
         "Odd Leaf": {"Sickening": False, "Satiating": False, "Bonus": 0, "Meal": False},
         "Rusty Nail": {"Sickening": False, "Satiating": False, "Bonus": -5, "Meal": False},
         "Worn Shoe": {"Sickening": False, "Satiating": True, "Bonus": -5, "Meal": False},
         "Dirt Clod": {"Sickening": False, "Satiating": False, "Bonus": 0, "Meal": False},
         "Worm Larvae": {"Sickening": True, "Satiating": False, "Bonus": 0, "Meal": False},
         "Moth Larvae": {"Sickening": True, "Satiating": False, "Bonus": 0, "Meal": False},
         "Candlewick": {"Sickening": False, "Satiating": False, "Bonus": 0, "Meal": False},
         "Basil": {"Sickening": False, "Satiating": False, "Bonus": 3, "Meal": False},
         "Sunleaf": {"Sickening": False, "Satiating": False, "Bonus": 30, "Meal": False},
         "Sharpleaf": {"Sickening": True, "Satiating": False, "Bonus": -10, "Meal": False},
         "Yellow Berries": {"Sickening": True, "Satiating": True, "Bonus": 2, "Meal": False},
         "Red Berries": {"Sickening": False, "Satiating": True, "Bonus": 3, "Meal": False},
         "Green Berries": {"Sickening": False, "Satiating": False, "Bonus": 0, "Meal": False},
         "Crumbleroot": {"Sickening": False, "Satiating": True, "Bonus": -1, "Meal": False},
         "Birdstalk": {"Sickening": True, "Satiating": False, "Bonus": 10, "Meal": False},
         "Crumbleroot Steak": {"Sickening": False, "Satiating": True, "Bonus": 8, "Meal": True},
         "Sharpleaf Eggs": {"Sickening": False, "Satiating": True, "Bonus": 0, "Meal": True},
         "Basil Berry Stew": {"Sickening": False, "Satiating": True, "Bonus": 5, "Meal": True},
         "Berry Syrup": {"Sickening": False, "Satiating": False, "Bonus": 2, "Meal": True},
         "Braised Boar Shank": {"Sickening": False, "Satiating": True, "Bonus": 20, "Meal": True},
}
COOKING_CHART = {"Raw Boar Meat": "Roasted Boar Shank",
               "Raw Elk Leg": "Roasted Elk Leg",
               "Raw Venison Steak": "Venison Steak",
               "Hawk Egg": "Boiled Hawk Egg",
               "Sparrow Egg": "Boiled Sparrow Egg",
}
MEAL_CHART = {"Crumbleroot Steak": ["Crumbleroot", "Raw Venison Steak"],
            "Sharpleaf Eggs": ["Sharpleaf", "Hawk Egg"],
            "Sharpleaf Eggs": ["Sharpleaf", "Sparrow Egg"],
            "Basil Berry Stew": ["Basil", "Red Berries", "Raw Elk Leg"],
            "Berry Syrup": ["Sunleaf", "Yellow Berries", "Red Berries", "Green Berries"],
            "Braised Boar Shank": ["Berry Syrup", "Raw Boar Meat"],
}
HIDDEN_CLASSES = {"Politician": {"Description": "Fairly average health and damage, low stamina, \
                               incredibly high power. \n Good for making a big production without \
                               getting anything done.",
                               "Stats": {"Health": 35, "MaxHealth": 35, "Damage": 20, "Stamina": 15,
                                         "MaxStamina": 15, "Fatigue": 0, "Defense": 6, "Power": 25},
                              },
}
CLASS_ABILITIES = {"Hunter": ["Forage"], "Prince": ["Scheme"],
                 "Farmer": ["Forage"], "Traveller": ["Trek"],
                 "Politician": ["Scheme"],
}
FORAGE_TABLE = {"Basil": [1, 10], "Sharpleaf": [11, 19], "Sunleaf": [20, 27],
              "Yellow Berries": [28, 35], "Red Berries": [36, 49],
              "Green Berries": [50, 64], "Crumbleroot": [65, 72],
              "Birdstalk": [73, 80],
}
DESCRIPTIONS = {"OLD BONE": ["This long, dirt stained bone appears to be some \n long-legged animal's femur.", "This curved piece of bone appears to be a chip from some creature's \n skull, but you can't tell if it's from an animal... or a human."],
                "OWL PELLET": ["This is a damp, feathery-looking pellet regurgitated from an owl. \n Bits of bone and the like stick out from inside."],
                "SHINY STONE": ["This off-white stone glints and shines when held at the \n right angle."],
                "SHREDDED HOOD": ["This green shred of cloth appears to be from the hood of a cloak.", "This red shred of cloth appears to be from the hood of a cloak."],
                "DEAD MOUSE": ["This mouse is soaked, bloated, and stinking. It appears to have \n drowned."],
                "TORN PARCHMENT": ["The writing on this bit of parchmen is no longer ledgible."],
                "HARDENED TWIG": ["This twig is so full of knots that, as full as it is of water, it is \n pratically unbreakable."],
                "GLASS SHARD": ["This jagged piece of glass is clear and unblemished."],
                "RABBIT FOOT": ["This brought no luck to its previous owner."],
                "ODD LEAF": ["This green leaf smells pleasantly sweet.", "This reddish leaf exudes some sort of oil, which seems \n to have kept it dry."],
                "RUSTY NAIL": ["This nail is rusted nearly all the way through. It is no \n longer usable."],
                "WORN SHOE": ["This appears to be the shoe of a small child. The sole has been worn through.", "This was once the shoe of a farmer. Its thick leather heel is caked in mud."],
                "WHEEL AXLE": ["This thick wooden dowel was once the axle of a cart."],
                "DIRT CLOD": ["It's really more like mud at this point."],
                "LOVE LETTER": ["You can't tell what has ruined this letter more, the rain, \n or the tears of its writer."],
                "YELLOW BEETLE": ["This beetle has bright yellow markings on its wings."],
                "RED BEETLE": ["This beetle has blood red legs."],
                "ORANGE BEETLE": ["This beetle has metallic orange wings."],
                "GREEN BEETLE": ["This beetle is oily green."],
                "BLUE BEETLE": ["This beetle flashes a bright blue underwing."],
                "INDIGO BEETLE": ["This beetle's dark indigo seems to blend into the sky."],
                "VIOLET BEETLE": ["This beetle has two violet teardrops on its wings."],
                "WORM LARVAE": ["Eww."],
                "MOTH LARVAE": ["It's kinda floppy."],
                "STRIKE-STONE": ["This sharp, slate-like stone produces a spark when struck."],
                "CLOTH DOLL": ["This small puppet, once the toy of some small child, \n lies soaked and ruined in the mud."],
                "BROKEN AMULET": ["This amulet, a large ruby set in a silver disk, has \n cracked down the middle."],
                "CANDLEWICK": ["This long, white string coated in wax has survived the rain."],
                "MOLDY TOME": ["The soggy, ruined pages of this book have molded through."],
                "CARK DECK": ["You don't really feel in the mood for games."],
                "WOODEN DICE": ["These look perfect for rehashing."],
                "HAWK EGG": ["This smallish, ivory egg might make a good dinner."],
                "SPARROW EGG": ["This greyish egg fell out of a sparrow's nest."],
                "EGG SAC": ["This spider's egg sac sticks to nearl everything it touches. \n You hope it doesn't hatch..."],
                "DAMP STRING": ["This string just so happens to be damp."],
                "BARREL": ["This old supply barrel has cracked from water damage, but its \n iron binding still look good."],
                "SACK": ["This burlap sack would once have been used to hold foodstuffs."],
                "CRATE": ["You aren't quite sure where this crate came from."],
                "EAGLE'S NEST": ["The creator of this nest is away..."],
                "CHEST": ["This chest is water-rotted and musky."],
                "HOLLOW TREE": ["This tree has died and rotted inside."],
                "CORPSE": ["This is the corpse of one of the previous \n inhabitants of this place.", "This corpse has become unusually bloated by the water."],
                "WINESKIN": ["This was once full of wine. Now, it is home to whatever was able \n to make it inside."],
                "HOLE": ["You aren't sure what made this hole... perhaps a snake, or a small rodent?"],
                "ANCIENT SHIPWRECK": ["This ship was brought ashore long before the storms stated, now \n only a rotting hull."],
                "OVERTURNED BOWL": ["Why are bowls always overturned?"],
                "BACKPACK": ["This backpack is made from thick leather, with a long leather flap \n and a buckled strap."],
                "WRECKED SHRINE": ["Raised by some sort of monstrous race, this crude stone shrine has \n lon since fallen into disrepair."],
                "COFFIN": ["This wooden coffin is no longer sealed..."],
                "VASE": ["This clay vase has been carved with several animals on the side.", "This plain vase is chipped an cracked with use."],
                "CHAMBER POT": ["This plain chamber pot would once have been stored under a cabinet."],
                "ABANDONED COINPURSE": ["Once a prized hiding place of gold, this coinpurse has been left in the mud."],
                "RABBIT HOLE": ["This was a rabbit's home... until you scared it off. You monster."],
                "TALL GRASS": ["The grass here has flourished from the rain, growing tall and strong."],
                "ABANDONED CART": ["After its wheel broke, this cart was left to rot."],
                "AVALANCHE-BURIED CARAVAN": ["The mountains came rolling down here, trapping a lone caravan."],
                }
MONSTER_DICT = [#Undead
                "Zombie", "Wraith", "Skeleton", "Ghoul",
                #Humanoids
                "Goblin Youngling", "Goblin Grunt", "Goblin",
                "Goblin Warrior", "Goblin Warlord", "Orc", "Orc Hunter",
                "Orc Prophet",
                #Wildlife
                "Giant Rat", "Wolf", "Wild Boar", "Elk", "Stag",
                "Giant Fire Beetle", "Giant Hawk",
                #Spider
                "Giant Wolf Spider", "Giant Black Widow", "Stone-Fang Spider"]
MONSTER_COMPENDIUM = {#Undead
                      "Zombie": {"HPModifier": [10, 13], "DamageModifier": [1, 3],
                                 "Biomes": ["some Ruins", "a Graveyard", "a Dungeon"],
                                 "Carries": ["Misc"], "MaxLevel": (6), "Epic": False,
                                 "ChampionName": ("Grizzled Zombie"), "XP": (7),
                                 },
                      "Wraith": {"HPModifier": [17, 21], "DamageModifier": [4, 6],
                                 "Biomes": ["a Graveyard"],
                                 "Carries": [], "MaxLevel": (7), "Epic": True,
                                 "EpicType": ("Undead"),
                                 "ChampionName": ("Dread Wraith"), "XP": (20)
                                 },
                      "Skeleton": {"HPModifier": [8, 13], "DamageModifier": [1, 3],
                                   "Biomes": ["some Ruins", "a Graveyard", "a Dungeon"],
                                   "Carries": ["Item"], "Items": ["Skull", "Old Bone",
                                                                  "Old Bone"],
                                   "MaxLevel": (6), "Epic": False,
                                   "ChampionName": ("Shrieking Skeleton"), "XP": (6),
                                   },
                      "Ghoul": {"HPModifier": [7, 9], "DamageModifier": [4, 5],
                                "Biomes": ["the Mountains"],
                                "Carries": [], "MaxLevel": (4), "Epic": False,
                                "ChampionName": ("Fetid Ghoul"), "XP": (4),
                                },
                      #Wildlife
                      "Giant Rat": {"HPModifier": [8, 11], "DamageModifier": [1, 3],
                                    "Biomes": ["some Ruins", "the Plains", "a Forest",
                                               "a Dungeon", "a Graveyard"],
                                    "Carries": [], "MaxLevel": (5), "Epic": False,
                                    "ChampionName": ("Giant Bloodied Rat"), "XP": (5),
                                    },
                      "Wolf": {"HPModifier": [14, 17], "DamageModifier": [5, 7],
                               "Biomes": ["a Forest", "the Plains"], "Carries": [],
                               "MaxLevel": (7), "Epic": False,
                               "ChampionName": ("Alpha Wolf"), "XP": (10),
                               },
                      "Wild Boar": {"HPModifier": [25, 35], "DamageModifier": [6, 7],
                                    "Biomes": ["a Forest", "the Plains"],
                                    "Carries": [None, "Item"], "Items": ["Raw Boar Shank"],
                                    "MaxLevel": (12), "Epic": False,
                                    "ChampionName": ("Ferocious Boar"), "XP": (20),
                                    },
                      "Elk": {"HPModifier": [8, 11], "DamageModifier": [2, 6],
                              "Biomes": ["a Forest", "the Plains"],
                              "Carries": [None, "Item"],
                              "Items": ["Raw Elk Leg"], "MaxLevel": (6),
                              "Epic": False, "ChampionName": ("Enraged Elk"), "XP": (10),
                              },
                      "Stag": {"HPModifier": [7, 8], "DamageModifier": [1, 2],
                               "Biomes": ["a Forest", "the Plains"],
                               "Carries": [None, "Item"], "Items": ["Raw Venison Steak"],
                               "MaxLevel": (2), "Epic": False,
                               "ChampionName": ("Whitefell Stag"), "XP": (3),
                               },
                      "Giant Fire Beetle": {"HPModifier": [7, 8], "DamageModifier": [6, 7],
                                            "Biomes": ["a Forest", "the Plains",
                                                       "some Ruins"],
                                            "Carries": [], "MaxLevel": (2),
                                            "Epic": False,
                                            "ChampionName": ("Giant Fire Beetle"),
                                            "XP": (10),
                                            },
                      "Giant Hawk": {"HPModifier": [5, 6], "DamageModifier": [5, 7],
                                     "Biomes": ["the Mountains"],
                                     "Carries": [None, "Item"], "Items": ["Dead Mouse"],
                                     "MaxLevel": (4),
                                     "Epic": False, "ChampionName": ("Ancient Hawk"),
                                     "XP": (5),
                                     },
                      #Spider
                      "Giant Wolf Spider": {"HPModifier": [4, 6],
                                            "DamageModifier": [2, 6],
                                            "Biomes": ["a Forest", "the Plains",
                                                       "a Graveyard", "a Dungeon"],
                                            "Carries": [], "MaxLevel": (6), "Epic": False,
                                            "ChampionName": ("Starving Wolf Spider"),
                                            "XP": (7),
                                            },
                      "Giant Black Widow": {"HPModifier": [10, 17],
                                            "DamageModifier": [5, 8],
                                            "Biomes": ["a Forest", "the Plains",
                                                       "a Dungeon"],
                                            "Carries": [], "MaxLevel": (7), "Epic": True,
                                            "EpicType": ("Spider"),
                                            "ChampionName": ("Black Widow Brood Mother"),
                                            "XP": (20),
                                            },
                      "Stone-Fang Spider": {"HPModifier": [10, 12], "DamageModifier": [2, 3],
                                            "Biomes": ["the Mountains"], "Carries": [],
                                            "MaxLevel": (6), "Epic": False,
                                            "ChampionName": ("Tar-Fang Spider"),
                                            "XP": (4),
                                            },
                      #Humanoids
                      "Orc": {"HPModifier": [15, 19], "DamageModifier": [7, 10],
                              "Biomes": ["a Forest", "the Mountains", "some Ruins",
                                         "a Castle"], "Carries": ["Misc"],
                              "MaxLevel": (9), "Epic": False,
                              "ChampionName": ("Orc Berserker"), "XP": (11),
                              },
                      "Orc Hunter": {"HPModifier": [17, 24], "DamageModifier": [8, 11],
                                     "Biomes": ["a Forest", "the Mountains", "some Ruins",
                                               "a Castle"], "Carries": ["Misc", "Usables"],
                                     "MaxLevel": (10), "Epic": False,
                                     "ChampionName": ("Orc Sharpshooter"), "XP": (13),
                                     },
                      "Orc Prophet": {"HPModifier": [12, 16], "DamageModifier": [15, 20],
                                      "Biomes": ["a Forest", "the Mountains", "some Ruins",
                                                 "a Castle"], "Carries": ["Usables"],
                                      "MaxLevel": (12), "Epic": False,
                                      "ChampionName": ("Orc Deathspeaker"), "XP": (20),
                                      },
                      "Goblin Youngling": {"HPModifier": [9, 10], "DamageModifier": [2, 3],
                                           "Biomes": ["some Ruins", "the Plains",
                                                      "the Mountains", "a Forest"],
                                           "Carries": ["Misc", "Misc", "Item"],
                                           "Items": ["Strike-Stone"], "MaxLevel": (5),
                                           "Epic": False, "ChampionName":
                                           ("Goblin Prodigy"), "XP": (3),
                                           },
                      "Goblin Grunt": {"HPModifier": [15, 20], "DamageModifier": [4, 9],
                                       "Biomes": ["some Ruins", "the Plains",
                                                  "the Mountains", "a Forest"],
                                       "Carries": ["Misc", "Gold", "Item"], "Items": ["Ornamental Dagger"],
                                       "MaxLevel": (10),
                                       "Epic": False, "ChampionName": ("Goblin Hermit"),
                                       "XP": (10),
                                       },
                      "Goblin": {"HPModifier": [20, 30], "DamageModifier": [5, 11],
                                 "Biomes": ["some Ruins", "the Plains", "the Mountains",
                                            "a Forest"],
                                 "Carries": ["Misc", "Gold"], "MaxLevel": (12),
                                 "Epic": False, "ChampionName": ("Goblin Veteran"),
                                 "XP": (16),
                                 },
                      "Goblin Warrior": {"HPModifier": [25, 34],
                                         "DamageModifier": [10, 15],
                                         "Biomes": ["some Ruins", "the Plains",
                                                    "the Mountains", "a Forest"],
                                         "Carries": ["Usables", "Gold"], "MaxLevel": (15),
                                         "Epic": False,
                                         "ChampionName": ("Goblin General"), "XP": (24),
                                         },
                      "Goblin Warlord": {"HPModifier": [40, 45],
                                         "DamageModifier": [15, 20],
                                         "Biomes": ["some Ruins", "the Plains",
                                                    "the Mountains", "a Forest"],
                                         "Carries": ["Usables"], "MaxLevel": (20),
                                         "Epic": False,
                                         "ChampionName": ("Goblin Lord"), "XP": (35),
                                         },
                      }
TRAVELLERS = {"Bard": {"Name": "Bard",
                       "FirstPhrase": ">The man before you carries a stringed instrument on his back, \n and wears a jauntily-colored cloak. He says, \n \"Good day! It is always nice to see another traveller. \n I am the bard. If you don't mind, I would like to play a song...\" \n Without waiting for a response, he pulls out his instrument \n and begins to strum.",
                       "Phrases": ["Good "],
                       "EffectsList": ["Invigorating Song", "Strengthening Song", "Song of Courage"],
                       "Effects": {"Invigorating Song": {"ASE": status_effects.invigorating, "Description": ">The bard plays a joyous, lively song."},
                                   "Strengthening Song": {"ASE": status_effects.strengthening, "Description": ">The bard plays a strong, steady tune, and you find yourself \n tapping your foot along with the rhythm."},
                                   "Song of Courage": {"ASE": status_effects.encouragement, "Description": ">The bard plays a song of piercing clarity and power."}
                                   },
                       "ItemsList": [],
                       "SalesList": [],
                       "Sells": {},
                       },
              "Merchant": {"Name": "Merchant",
                           "FirstPhrase": "",
                           "Phrases": [""],
                           "EffectsList": [],
                           "Effects": {},
                           "ItemsList": ["Heaing Potion", "Red Apple", "Longsword", "Strike-Stone", "Pointed Stick", "Earthen 3 Longsword", "Rainwashed Dagger", "Raw Venison Steak", "Skull", "Musty Spellbook"],
                           "SalesList": [],
                           "Sells": {"Healing Potion": {"InvVal": "Healing Potion", "Price": 500},
                                     "Red Apple": {"InvVal": "Red Apple", "Price": 50},
                                     "Longsword": {"InvVal": {"Name": "Longsword", "Type": "Weapon", "Bonus": 8, "Power": 0, "Stamina": 0, "BonusType": "Add", "Defense": 0}, "Price": 100},
                                     "Strike-Stone": {"InvVal": "Strike-Stone", "Price": 200},
                                     "Pointed Stick": {"InvVal": {"Name": "Pointed Stick", "Type": "Weapon", "Bonus": 0, "Power": 0, "Stamina": 0, "BonusType": "Add", "Defense": 0}, "Price": 10},
                                     "Earthen 3 Longsword": {"InvVal": {"Name": "Earthen 3 Longsword", "Enchanted": True, "Type": "Weapon", "Bonus": 18, "Power": 0, "Stamina": 0, "BonusType": "Add", "Defense": 0}, "Price": 500},
                                     "Rainwashed Dagger": {"InvVal": {"Name": "Rainwashed Dagger", "Type": "Weapon", "Bonus": 10, "Power": 20, "Stamina": 10, "BonusType": "Add", "Defense": 10}, "Price": 2000},
                                     "Raw Venison Steak": {"InvVal": "Raw Venison Steak", "Price": 250},
                                     "Skull": {"InvVal": "Skull", "Price": 100},
                                     "Musty Spellbook": {"InvVal": "Musty Spellbook", "Price": 700},
                                     },
                           },
                }
FIRESTARTING_PROBABILITIES = {"Biomes": {"a Forest": 60, "the Plains": 30,
                                         "the Mountains": 10, "some Ruins": 40,
                                         "a Castle": 50, "a Dungeon": 40,
                                         "a Graveyard": 30},
                              "Tinder": {"OWL PELLET": 5, "SHREDDED HOOD": 10,
                                         "TORN PARCHMENT": 20, "HARDENED TWIG": 20,
                                         "ODD LEAF": 5, "WHEEL AXLE": 10,
                                         "LOVE LETTER": 25, "CLOTH DOLL": 15,
                                         "CANDLEWICK": 10, "MOLDY TOME": 5,
                                         "CARD DECK": 10, "POINTED STICK": 14,
                                         "WOODEN DICE": 5, "CLUB": 10, "QUARTERSTAFF": 10,
                                         "PADDED ROBE": 8, "MUSTY SPELLBOOK": 10,
                                         "CRUMBLING PAPYRUS": 15, "BOW": 10,
                                         "CROSSBOW": 10, "GREATCLUB": 10}
                             }
USABLES = {"Pointed Stick": {"Appearance Level": 0, "Type": "Weapon", "Bonus": 0,
                             "BonusType": "Add", "Power": 0, "Defense": 0, "Stamina": 0,
                            },
           "Soaked Tunic": {"Appearance Level": 0, "Type": "Armor", "Bonus": 0,
                            "Retaliation": 0, "Power": 0, "Damage": 0, "Stamina": 0,
                            "SentenceStructure": " a ",
                            },
           "Goblin's Tunic": {"Appearance Level": 0, "Type": "Armor", "Bonus": 3,
                              "BonusType": "Add", "Power": -1, "Damage": 0, "Stamina": 5,
                              "SentenceStructure": " a ",
                             },
           "Bandage Roll": {"Appearance Level": 1, "Type": "Bandage", "Bonus": 5,
                           },
           "Scroll of Satiations": {"Appearance Level": 1, "Type": "Scroll", "Bonus": None,
                                   },
           "Dagger": {"Appearance Level": 1, "Type": "Weapon", "Bonus": 5, "BonusType": "Add",
                      "Power": 0, "Defense": 0, "Stamina": 0,
                     },
           "Longsword": {"Appearance Level": 1, "Type": "Weapon", "Bonus": 8, "BonusType": "Add",
                         "Power": 0, "Defense": 0, "Stamina": 0,
                        },
           "Axe": {"Appearance Level": 1, "Type": "Weapon", "Bonus": 7, "BonusType": "Add",
                   "Power": 0, "Defense": 0, "Stamina": 0,
                  },
           "Club": {"Appearance Level": 1, "Type": "Weapon", "Bonus": 1.3, "BonusType": "Mult",
                    "Power": 0, "Defense": 0, "Stamina": 0,
                   },
           "Mace": {"Appearance Level": 1, "Type": "Weapon", "Bonus": 1.5, "BonusType": "Mult",
                    "Power": 0, "Defense": 0, "Stamina": 0,
                   },
           "Quarterstaff": {"Appearance Level": 1, "Type": "Weapon", "Bonus": 1.5,
                            "BonusType": "Mult", "Power": 0, "Defense": 0, "Stamina": 0,
                           },
           "Padded Robe": {"Appearance Level": 1, "Type": "Armor", "Bonus": 3, "Retaliation": 0,
                           "Power": 0, "Damage": 0, "Stamina": 0, "SentenceStructure": " a ",
                          },
           "Leather Chestplate": {"Appearance Level": 1, "Type": "Armor", "Bonus": 8,
                                  "Retaliation": 0, "Power": 0, "Damage": 0, "Stamina": -2,
                                  "SentenceStructure": " ",
                                 },
           "Healing Potion": {"Appearance Level": 1, "Type": "Potion", "Bonus": 10,
                             },
           "Musty Spellbook": {"Appearance Level": 2, "Type": "Scroll 1",
                              },
           "Crumbling Papyrus": {"Appearance Level": 2, "Type": "Scroll 1",
                                },
           "Sutures": {"Appearance Level": 5, "Type": "Bandage", "Bonus": 20,
                      },
           "Bow": {"Appearance Level": 5, "Type": "Weapon", "Bonus": 12, "BonusType": "Add",
                   "Power": 0, "Defense": 0, "Stamina": 0,
                  },
           "Rapier": {"Appearance Level": 5, "Type": "Weapon", "Bonus": 15, "BonusType": "Add",
                      "Power": 0, "Defense": 0, "Stamina": 0,
                     },
           "Pick": {"Appearance Level": 5, "Type": "Weapon", "Bonus": 12, "BonusType": "Add",
                    "Power": 0, "Defense": 0, "Stamina": 0,
                   },
           "Shortsword": {"Appearance Level": 5, "Type": "Weapon", "Bonus": 13,
                          "BonusType": "Add", "Power": 0, "Defense": 0, "Stamina": 0,
                         },
           "Shuriken": {"Appearance Level": 7, "Type": "Weapon", "Bonus": 15, "BonusType": "Add",
                        "Power": 0, "Defense": 0, "Stamina": 2,
                       },
           "Throwing Dagger": {"Appearance Level": 7, "Type": "Weapon", "Bonus": 18,
                               "BonusType": "Add", "Power": 0, "Defense": 0, "Stamina": 2,
                              },
           "Throwing Axe": {"Appearance Level": 7, "Type": "Weapon", "Bonus": 14,
                            "BonusType": "Add", "Power": 0, "Defense": 0, "Stamina": 0,
                           },
           "Throwing Hammer": {"Appearance Level": 7, "Type": "Weapon", "Bonus": 2.4,
                               "BonusType": "Mult", "Power": 0, "Defense": 0, "Stamina": 0,
                              },
           "Scale Mail": {"Appearance Level": 7, "Type": "Armor", "Bonus": 19, "Retaliation": 0,
                          "Power": 0, "Damage": 0, "Stamina": 0, "SentenceStructure": " ",
                         },
           "Rejuvination Potion": {"Appearance Level": 7, "Type": "Potion", "Bonus": 20,
                                  },
           "Stitches": {"Appearance Level": 10, "Type": "Bandage", "Bonus": 50,
                       },
           "Khopesh": {"Appearance Level": 10, "Type": "Weapon", "Bonus": 22, "BonusType": "Add",
                       "Power": 0, "Defense": 0, "Stamina":  0,
                      },
           "Crossbow": {"Appearance Level": 10, "Type": "Weapon", "Bonus": 24, "BonusType": "Add",
                        "Power": 0, "Defense": 2, "Stamina": 0,
                       },
           "Scroll": {"Appearance Level": 11, "Type": "Scroll 2",
                     },
           "Greataxe": {"Appearance Level": 15, "Type": "Weapon", "Bonus": 30, "BonusType": "Add",
                        "Power": 0, "Defense": 0, "Stamina": 0,
                       },
           "Greatsword": {"Appearance Level": 15, "Type": "Weapon", "Bonus": 27,
                          "BonusType": "Add", "Power": 0, "Defense": 0, "Stamina": 0,
                         },
           "Warhammer": {"Appearance Level": 15, "Type": "Weapon", "Bonus": 2.8,
                         "BonusType": "Mult", "Power": 0, "Defense": 0, "Stamina": 0,
                        },
           "Greatclub": {"Appearance Level": 15, "Type": "Weapon", "Bonus": 2.7,
                         "BonusType": "Mult", "Power": 0, "Defense": 0, "Stamina": 0,
                        },
           "Restoration Potion": {"Appearance Level": 15, "Type": "Potion", "Bonus": 30,
                                 },
           "Whispering Tome": {"Appearance Level": 17, "Type": "Scroll 3",
                              },
           "Maul": {"Appearance Level": 20, "Type": "Weapon", "Bonus": 3.4, "BonusType": "Mult",
                    "Power": 0, "Defense": 0, "Stamina": 0,
                   },
           "Morningstar": {"Appearance Level": 20, "Type": "Weapon", "Bonus": 3.7,
                           "BonusType": "Mult", "Power": 0, "Defense": 0, "Stamina": 0,
                          },
           "Falchion": {"Appearance Level": 20, "Type": "Weapon", "Bonus": 34, "BonusType": "Add",
                        "Power": 0, "Defense": 0, "Stamina": 0,
                       },
           "Scimitar": {"Appearance Level": 20, "Type": "Weapon", "Bonus": 37,
                        "BonusType": "Add", "Power": 0, "Defense": 0, "Stamina": 0,
                       },
           "Chain Mail": {"Appearance Level": 20, "Type": "Armor", "Bonus": 20, "Power": 0,
                          "Damage": 0, "Stamina": 0, "SentenceStructure": " "
                         },
           "Full Plate Armor": {"Appearance Level": 20, "Type": "Armor", "Bonus": 27,
                                "Retaliation": 0, "Power": 0, "Damage": 0, "Stamina": 0,
                                "SentenceStructure": " "
                               },
           "Rehabilitative Potion": {"Appearance Level": 50, "Type": "Potion", "Bonus": 100,
                                    },
           "Sky Staff": {"Appearance Level": 50, "Type": "Weapon", "Bonus": 5, "BonusType": "Mult",
                         "Power": 10, "Defense": 0, "Stamina": 0,
                        },
           "Storm Plate": {"Appearance Level": 50, "Type": "Armor", "Bonus": 40, "Retaliation": 10,
                           "Power": 10, "SentenceStructure": " the "
                           },
           }
USABLES_LIST = ["Dagger", "Longsword", "Axe", "Club", "Mace", "Quarterstaff",
              "Padded Robe", "Leather Chestplate", "Healing Potion",
              "Musty Spellbook", "Crumbling Papyrus", "Bow", "Rapier",
              "Pick", "Shortsword", "Shuriken", "Throwing Dagger",
              "Throwing Axe", "Throwing Hammer", "Scale Mail",
              "Rejuvination Potion", "Khopesh", "Crossbow",
              "Greataxe", "Greatsword", "Warhammer", "Greatclub",
              "Restoration Potion", "Maul", "Morningstar", "Falchion",
              "Scimitar", "Chain Mail", "Full Plate Armor",
              "Rehabilitative Potion", "Sky Staff", "Storm Plate"
             ]
PREFIX_MODIFIERS = {"Flaming 1": {"WeaponEffect": ("Bonus"),
                                  "ArmorEffect": ("Retaliation"),
                                  "Bonus": (5),
                                 },
                    "Flaming 2": {"WeaponEffect": ("Bonus"),
                                  "ArmorEffect": ("Retaliation"),
                                  "Bonus": (7),
                                 },
                    "Flaming 3": {"WeaponEffect": ("Bonus"),
                                  "ArmorEffect": ("Retaliation"),
                                  "Bonus": (10),
                                 },
                    "Earthen 1": {"WeaponEffect": ("Bonus"),
                                  "ArmorEffect": ("Bonus"),
                                  "Bonus": (5),
                                 },
                    "Earthen 2": {"WeaponEffect": ("Bonus"),
                                  "ArmorEffect": ("Bonus"),
                                  "Bonus": (7),
                                 },
                    "Earthen 3": {"WeaponEffect": ("Bonus"),
                                  "ArmorEffect": ("Bonus"),
                                  "Bonus": (10),
                                 },
                    "Dampened 1": {"WeaponEffect": ("Power"),
                                   "ArmorEffect": ("Power"),
                                   "Bonus": (5),
                                  },
                    "Dampened 2": {"WeaponEffect": ("Power"),
                                   "ArmorEffect": ("Power"),
                                   "Bonus": (7),
                                  },
                    "Dampened 3": {"WeaponEffect": ("Power"),
                                   "ArmorEffect": ("Power"),
                                   "Bonus": (10),
                                  },
                    "Aerial 1": {"WeaponEffect": ("Bonus"),
                                 "ArmorEffect": ("Stamina"),
                                 "Bonus": (5),
                                },
                    "Aerial 2": {"WeaponEffect": ("Bonus"),
                                 "ArmorEffect": ("Stamina"),
                                 "Bonus": (7),
                                },
                    "Aerial 3": {"WeaponEffect": ("Bonus"),
                                 "ArmorEffect": ("Stamina"),
                                 "Bonus": (10),
                                },
                    "Lucky": {"WeaponEffect": ("Bonus"),
                              "ArmorEffect": ("Bonus"),
                              "Bonus": (7),
                             },
                    "Good": {"WeaponEffect": ("Defense"),
                             "ArmorEffect": ("Bonus"),
                             "Bonus": (6),
                            },
                    "Evil": {"WeaponEffect": ("Bonus"),
                             "ArmorEffect": ("Retaliation"),
                             "Bonus": (6),
                            },
                    "Empowered": {"WeaponEffect": ("Power"),
                                  "ArmorEffect": ("Power"),
                                  "Bonus": (19),
                                 },
                    "Deadened": {"WeaponEffect": ("Power"),
                                 "ArmorEffect": ("Power"),
                                 "Bonus": (-19),
                                },
                    "Well-Used": {"WeaponEffect": ("Bonus"),
                                  "ArmorEffect": ("Bonus"),
                                  "Bonus": (-3),
                                 },
                    "Rusted": {"WeaponEffect": ("Bonus"),
                               "ArmorEffect": ("Bonus"),
                               "Bonus": (-6),
                              },
                    "Deplorable": {"WeaponEffect": ("Bonus"),
                                   "ArmorEffect": ("Bonus"),
                                   "Bonus": (-9),
                                  },
                    "Ancient": {"WeaponEffect": ("Power"),
                                "ArmorEffect": ("Power"),
                                "Bonus": (10),
                               },
                    "Silent": {"WeaponEffect": ("Stamina"),
                               "ArmorEffect": ("Stamina"),
                               "Bonus": (14),
                              },
                    "Damascan": {"WeaponEffect": ("Defense"),
                                 "ArmorEffect": ("Damage"),
                                 "Bonus": (10),
                                },
                    }
                    